"""add blog likes and comments

Revision ID: 2469b47106ea
Revises: 8623462fae13
Create Date: 2026-06-17 19:09:40.421400

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


revision = '2469b47106ea'
down_revision = '8623462fae13'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('contact_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_user_id'), 'feedback', ['user_id'], unique=False)
    op.create_table('blog_comment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('blog_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['blog_id'], ['blog.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['blog_comment.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blog_comment_blog_id'), 'blog_comment', ['blog_id'], unique=False)
    op.create_index(op.f('ix_blog_comment_parent_id'), 'blog_comment', ['parent_id'], unique=False)
    op.create_index(op.f('ix_blog_comment_user_id'), 'blog_comment', ['user_id'], unique=False)
    op.create_table('blog_like',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('blog_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['blog_id'], ['blog.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blog_like_blog_id'), 'blog_like', ['blog_id'], unique=False)
    op.create_index(op.f('ix_blog_like_user_id'), 'blog_like', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blog_like_user_id'), table_name='blog_like')
    op.drop_index(op.f('ix_blog_like_blog_id'), table_name='blog_like')
    op.drop_table('blog_like')
    op.drop_index(op.f('ix_blog_comment_user_id'), table_name='blog_comment')
    op.drop_index(op.f('ix_blog_comment_parent_id'), table_name='blog_comment')
    op.drop_index(op.f('ix_blog_comment_blog_id'), table_name='blog_comment')
    op.drop_table('blog_comment')
    op.drop_index(op.f('ix_feedback_user_id'), table_name='feedback')
    op.drop_table('feedback')
    # ### end Alembic commands ###
