"""add comments_enabled to blog

Revision ID: 5075e62e1883
Revises: 2469b47106ea
Create Date: 2026-06-17 19:15:39.262700

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


revision = '5075e62e1883'
down_revision = '2469b47106ea'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('comments_enabled', sa.Boolean(), nullable=False, server_default='true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog', 'comments_enabled')
    # ### end Alembic commands ###
