"""add public flags to contact fields

Revision ID: 7d90fe6b64e3
Revises: 356e419a60a5
Create Date: 2026-06-13 12:01:53.889730

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

revision = '7d90fe6b64e3'
down_revision = '356e419a60a5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_notification_user_id', table_name='notification')
    op.drop_table('notification')
    op.add_column('extra_contact', sa.Column('linkedin_public', sa.Boolean(), nullable=False))
    op.add_column('extra_contact', sa.Column('facebook_public', sa.Boolean(), nullable=False))
    op.add_column('extra_contact', sa.Column('instagram_public', sa.Boolean(), nullable=False))
    op.add_column('extra_contact', sa.Column('website_public', sa.Boolean(), nullable=False))
    op.add_column('extra_contact', sa.Column('line_id_public', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('extra_contact', 'line_id_public')
    op.drop_column('extra_contact', 'website_public')
    op.drop_column('extra_contact', 'instagram_public')
    op.drop_column('extra_contact', 'facebook_public')
    op.drop_column('extra_contact', 'linkedin_public')
    op.create_table('notification',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('body', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('link', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='notification_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='notification_pkey')
    )
    op.create_index('ix_notification_user_id', 'notification', ['user_id'], unique=False)
    # ### end Alembic commands ###
