"""add blog likes and comments

Revision ID: 8623462fae13
Revises: 1919d14b75c4
Create Date: 2026-06-17 19:06:48.994446

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

revision = '8623462fae13'
down_revision = '1919d14b75c4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_feedback_user_id', table_name='feedback')
    op.drop_table('feedback')
    op.drop_index('ix_blog_comment_blog_id', table_name='blog_comment')
    op.drop_index('ix_blog_comment_parent_id', table_name='blog_comment')
    op.drop_index('ix_blog_comment_user_id', table_name='blog_comment')
    op.drop_table('blog_comment')
    op.drop_index('ix_notification_user_id', table_name='notification')
    op.drop_table('notification')
    op.drop_index('ix_blog_like_blog_id', table_name='blog_like')
    op.drop_index('ix_blog_like_user_id', table_name='blog_like')
    op.drop_table('blog_like')
    op.drop_column('blog', 'comments_enabled')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('comments_enabled', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.create_table('blog_like',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('blog_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['blog_id'], ['blog.id'], name='blog_like_blog_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='blog_like_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='blog_like_pkey'),
    sa.UniqueConstraint('blog_id', 'user_id', name='uq_blog_like', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index('ix_blog_like_user_id', 'blog_like', ['user_id'], unique=False)
    op.create_index('ix_blog_like_blog_id', 'blog_like', ['blog_id'], unique=False)
    op.create_table('notification',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('body', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('link', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='notification_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='notification_pkey')
    )
    op.create_index('ix_notification_user_id', 'notification', ['user_id'], unique=False)
    op.create_table('blog_comment',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('blog_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('parent_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['blog_id'], ['blog.id'], name='blog_comment_blog_id_fkey'),
    sa.ForeignKeyConstraint(['parent_id'], ['blog_comment.id'], name='blog_comment_parent_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='blog_comment_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='blog_comment_pkey')
    )
    op.create_index('ix_blog_comment_user_id', 'blog_comment', ['user_id'], unique=False)
    op.create_index('ix_blog_comment_parent_id', 'blog_comment', ['parent_id'], unique=False)
    op.create_index('ix_blog_comment_blog_id', 'blog_comment', ['blog_id'], unique=False)
    op.create_table('feedback',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('message', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('contact_email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='feedback_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='feedback_pkey')
    )
    op.create_index('ix_feedback_user_id', 'feedback', ['user_id'], unique=False)
    # ### end Alembic commands ###
