"""add field_of_study is_current to education

Revision ID: dcd79d2679f3
Revises: ea6fd29f7d89
Create Date: 2026-06-13 15:16:47.089639

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


revision = 'dcd79d2679f3'
down_revision = 'ea6fd29f7d89'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE extra_contact DROP COLUMN IF EXISTS instagram_public')
    op.execute('ALTER TABLE extra_contact DROP COLUMN IF EXISTS facebook_public')
    op.execute('ALTER TABLE extra_contact DROP COLUMN IF EXISTS website_public')
    op.execute('ALTER TABLE extra_contact DROP COLUMN IF EXISTS linkedin_public')
    op.execute('ALTER TABLE extra_contact DROP COLUMN IF EXISTS line_id_public')
    op.execute("ALTER TABLE \"user\" ADD COLUMN IF NOT EXISTS linkedin_public BOOLEAN NOT NULL DEFAULT true")
    op.execute("ALTER TABLE \"user\" ADD COLUMN IF NOT EXISTS facebook_public BOOLEAN NOT NULL DEFAULT true")
    op.execute("ALTER TABLE \"user\" ADD COLUMN IF NOT EXISTS instagram_public BOOLEAN NOT NULL DEFAULT true")
    op.execute("ALTER TABLE \"user\" ADD COLUMN IF NOT EXISTS website_public BOOLEAN NOT NULL DEFAULT true")
    op.execute("ALTER TABLE \"user\" ADD COLUMN IF NOT EXISTS line_id_public BOOLEAN NOT NULL DEFAULT true")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'line_id_public')
    op.drop_column('user', 'website_public')
    op.drop_column('user', 'instagram_public')
    op.drop_column('user', 'facebook_public')
    op.drop_column('user', 'linkedin_public')
    op.add_column('extra_contact', sa.Column('line_id_public', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('extra_contact', sa.Column('linkedin_public', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('extra_contact', sa.Column('website_public', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('extra_contact', sa.Column('facebook_public', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('extra_contact', sa.Column('instagram_public', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
