"""add_new_user_fields

Revision ID: fd6031c61b41
Revises: 8f3946f2b44f
Create Date: 2026-06-08 15:48:46.881144

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

revision = 'fd6031c61b41'
down_revision = '8f3946f2b44f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_notification_user_id', table_name='notification')
    op.drop_table('notification')
    op.add_column('career', sa.Column('is_public', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('career', sa.Column('company_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('career', sa.Column('industry_sector', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('career', sa.Column('role_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('education', sa.Column('is_public', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('education', sa.Column('major2', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('education', sa.Column('minor1', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('education', sa.Column('scholarship_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('education', sa.Column('scholarship_bond', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('education', sa.Column('med_school', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('education', sa.Column('med_dual_degree', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('education', sa.Column('med_dual_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('education', sa.Column('med_dual_field', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('education', sa.Column('med_hospital', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('education', sa.Column('med_specialties', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('education', sa.Column('med_subspecialty', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('nickname', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('nickname_public', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('user', sa.Column('expected_grad_year', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('current_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('teach_start_year', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('teach_end_year', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('is_current_teacher', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('user', sa.Column('teach_department', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('instagram_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('contact_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('contact_email_public', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('user', sa.Column('place_level2', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('zodiac', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('chronotype', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('interests_public', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('user', sa.Column('research_interests', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('research_keywords', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('projects', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('publications', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('portfolio_links', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('languages', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('hobbies', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('kvis_fav_menu', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('kvis_fav_event', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('kvis_fav_area', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_user_is_current_teacher'), 'user', ['is_current_teacher'], unique=False)
    op.create_index(op.f('ix_user_teach_start_year'), 'user', ['teach_start_year'], unique=False)
    op.drop_column('user', 'current_elemental')
    op.drop_column('user', 'current_class')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('current_class', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('current_elemental', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_user_teach_start_year'), table_name='user')
    op.drop_index(op.f('ix_user_is_current_teacher'), table_name='user')
    op.drop_column('user', 'kvis_fav_area')
    op.drop_column('user', 'kvis_fav_event')
    op.drop_column('user', 'kvis_fav_menu')
    op.drop_column('user', 'hobbies')
    op.drop_column('user', 'languages')
    op.drop_column('user', 'portfolio_links')
    op.drop_column('user', 'publications')
    op.drop_column('user', 'projects')
    op.drop_column('user', 'research_keywords')
    op.drop_column('user', 'research_interests')
    op.drop_column('user', 'interests_public')
    op.drop_column('user', 'chronotype')
    op.drop_column('user', 'zodiac')
    op.drop_column('user', 'place_level2')
    op.drop_column('user', 'contact_email_public')
    op.drop_column('user', 'contact_email')
    op.drop_column('user', 'instagram_url')
    op.drop_column('user', 'teach_department')
    op.drop_column('user', 'is_current_teacher')
    op.drop_column('user', 'teach_end_year')
    op.drop_column('user', 'teach_start_year')
    op.drop_column('user', 'current_status')
    op.drop_column('user', 'expected_grad_year')
    op.drop_column('user', 'nickname_public')
    op.drop_column('user', 'nickname')
    op.drop_column('education', 'med_subspecialty')
    op.drop_column('education', 'med_specialties')
    op.drop_column('education', 'med_hospital')
    op.drop_column('education', 'med_dual_field')
    op.drop_column('education', 'med_dual_type')
    op.drop_column('education', 'med_dual_degree')
    op.drop_column('education', 'med_school')
    op.drop_column('education', 'scholarship_bond')
    op.drop_column('education', 'scholarship_type')
    op.drop_column('education', 'minor1')
    op.drop_column('education', 'major2')
    op.drop_column('education', 'is_public')
    op.drop_column('career', 'role_type')
    op.drop_column('career', 'industry_sector')
    op.drop_column('career', 'company_type')
    op.drop_column('career', 'is_public')
    op.create_table('notification',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('body', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('link', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='notification_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='notification_pkey')
    )
    op.create_index('ix_notification_user_id', 'notification', ['user_id'], unique=False)
    # ### end Alembic commands ###
