// ─── Constants ────────────────────────────────────────────────────────────────

export const CURRENT_STATUS_OPTIONS = [
  {
    group: "KVIS",
    options: [
      { value: "kvis_student", label: "KVIS Student" },
      { value: "kvis_faculty", label: "KVIS Faculty / Staff" },
    ],
  },
  {
    group: "Academic Track",
    options: [
      { value: "undergraduate", label: "Undergraduate Student" },
      { value: "masters", label: "Master's Student" },
      { value: "phd", label: "PhD Student" },
      { value: "postdoc", label: "Postdoctoral Researcher" },
    ],
  },
  {
    group: "Medical Track",
    options: [
      { value: "med_preclinical", label: "Pre-clinical (Years 1-3)" },
      { value: "med_clinical", label: "Clinical (Years 4-6)" },
      { value: "med_intern", label: "Internship / Transition Year" },
      { value: "med_residency", label: "Residency Training" },
      { value: "med_fellowship", label: "Fellowship Training" },
      { value: "med_staff", label: "Staff Physician / Specialist" },
    ],
  },
  {
    group: "Professional",
    options: [
      { value: "working_academia", label: "Working (Academia)" },
      { value: "working", label: "Working (Industry / Sector)" },
      { value: "founder", label: "Business Owner / Founder" },
      { value: "gap", label: "Gap Year / Exploring" },
    ],
  },
];

export const COMPANY_TYPES = [
  "Multinational Corporation (MNC)",
  "National Corporation / Local Enterprise",
  "State-Owned Enterprise (SOE)",
  "Government / Public Sector",
  "Academic / Research Institution",
  "Startup (Early to Late Stage)",
  "SME (Small to Medium Enterprise)",
  "NGO / Non-Profit / International Organization",
  "Self-Employed / Freelance / Business Owner",
  "Other",
];

export const INDUSTRY_SECTORS = [
  {
    group: "Public & Academic",
    options: [
      "Education, Training & Academia",
      "Public Sector, Government & Policy",
      "NGOs, Non-Profit & Social Impact",
    ],
  },
  {
    group: "Technology & Digital",
    options: [
      "Software, IT & Cloud Services",
      "Hardware, Semiconductors & Electronics",
      "Telecommunications & Networking",
    ],
  },
  {
    group: "Life Sciences & Health",
    options: [
      "Biotechnology, Pharma & Life Sciences",
      "Healthcare, Medical & MedTech",
    ],
  },
  {
    group: "Industrial & Engineering",
    options: [
      "Manufacturing, Aerospace & Automotive",
      "Energy, Utilities & Natural Resources",
      "Engineering & Technical Services",
    ],
  },
  {
    group: "Finance & Professional Services",
    options: [
      "Finance, Banking & Fintech",
      "Management Consulting & Strategy",
      "Legal, Accounting & Professional Services",
    ],
  },
  {
    group: "Environment & Infrastructure",
    options: [
      "Environment, Sustainability & Climate Tech",
      "Real Estate, Construction & Infrastructure",
      "Agriculture, Food & Forestry",
    ],
  },
  {
    group: "Consumer & Media",
    options: [
      "Consumer Goods, Retail & E-commerce",
      "Logistics, Supply Chain & Transportation",
      "Media, Entertainment & Creative Industries",
      "Hospitality, Tourism & Food Services",
    ],
  },
  { group: "Other", options: ["Other"] },
];

export const ROLE_TYPES = [
  "Education, Teaching & Academia",
  "R&D, Science & Laboratory",
  "Software & Systems Development",
  "Engineering & Technical Operations",
  "Data, AI & Analytics",
  "Healthcare & Clinical Practice",
  "Product, Project & Program Management",
  "Strategy, Consulting & Business Intelligence",
  "Quality, Regulatory & Compliance",
  "Executive & Corporate Leadership",
  "Design, Creative & UX/UI",
  "Finance, Accounting & Investment",
  "Operations, Supply Chain & Logistics",
  "Marketing, Communications & Public Relations",
  "Sales & Business Development",
  "Legal, Policy & Government Affairs",
  "Human Resources & People Operations",
  "Customer Success & Support",
  "Other",
];

export const SCHOLARSHIP_NAMES = [
  "King's Scholarship (เล่าเรียนหลวง)",
  "Olympiad Scholarship (โอลิมปิกวิชาการ)",
  "DPST (พสวท.)",
  "Vidyasirimedhi Scholarship (วิทยสิริเมธี)",
  "Other Thai Government Scholarship (OCSC / ก.พ.)",
  "ASEAN Scholarship",
  "MEXT Scholarship (Embassy Recommendation)",
  "MEXT Scholarship (University Recommendation)",
  "Country Scholarship",
  "University Scholarship",
  "Other",
];

export const SCHOLARSHIP_TYPES = [
  "Full Funding (Tuition + Stipend)",
  "Partial Funding / Tuition Waiver",
  "Research Assistantship (RA) / Teaching Assistantship (TA)",
];

export const SCHOLARSHIP_BOND = [
  "Bonded (Requires return of service/work)",
  "Non-bonded (No service requirement)",
];

export const CONTACT_TYPES = [
  "Email",
  "LinkedIn",
  "Facebook",
  "Instagram",
  "Line",
  "WhatsApp",
  "WeChat",
  "Discord",
  "Snapchat",
];

export const ZODIAC_SIGNS = [
  "Aries",
  "Taurus",
  "Gemini",
  "Cancer",
  "Leo",
  "Virgo",
  "Libra",
  "Scorpio",
  "Sagittarius",
  "Capricorn",
  "Aquarius",
  "Pisces",
];

export const CHRONOTYPES = ["Early Bird", "Night Owl"];

export const LANGUAGE_OPTIONS = [
  "Thai",
  "English",
  "Japanese",
  "Chinese",
  "Korean",
  "German",
  "French",
  "Spanish",
  "Hungarian",
  "Other",
];

export const LANGUAGE_PROFICIENCY = ["Native", "Fluent", "Learning"];

export const PORTFOLIO_TYPES = [
  "Google Scholar",
  "ResearchGate",
  "GitHub",
  "LinkedIn",
  "Personal Website/Blog",
  "ORCID",
  "Portfolio",
];

export const PROJECT_STATUSES = ["Ongoing", "Completed", "On-hold"];

export const INNOVATION_TYPES = [
  "Software / App / Platform",
  "Hardware / Deep Tech / Physical Product",
  "Research Patent / Intellectual Property",
  "Organization / Entity",
  "Book / Publication",
  "Song / Cover / Creative Release",
  "Other",
];

export const LAUNCH_STATUSES = [
  "Active / Launched",
  "In Development / Prototyping",
  "Archived / Closed",
];

export const RESEARCH_CATEGORIES = [
  {
    group: "Life Sciences & Bio-Innovation",
    options: [
      "Molecular, Cellular & Developmental Biology",
      "Microbiology, Immunology & Infectious Disease",
      "Genetics, Bioinformatics & Computational Biology",
      "Biochemistry, Structural Biology & Biophysics",
      "Biotechnology, Synthetic & Systems Biology",
      "Neuroscience & Behavioral Biology",
      "Physiology, Pharmacology & Toxicology",
      "Plant Science, Agriculture & Food Science",
      "Ecology & Evolutionary Biology",
    ],
  },
  {
    group: "Physics & Astronomy",
    options: [
      "Theoretical & Mathematical Physics",
      "Condensed Matter Physics",
      "Experimental Physics & Instrumentation",
      "Atomic, Molecular & Optical Physics",
      "Astronomy, Astrophysics, Cosmology & Space Science",
      "Quantum Computing, Quantum Information & Quantum Science",
      "Applied, Materials, Medical & Biophysics",
    ],
  },
  {
    group: "Chemistry & Material Science",
    options: [
      "Organic Chemistry",
      "Inorganic Chemistry",
      "Biochemistry & Chemical Biology",
      "Analytical Chemistry & Spectroscopy",
      "Physical Chemistry",
      "Computational & Theoretical Chemistry",
      "Materials & Nanoscience",
      "Energy, Sustainability & Green Chemistry",
    ],
  },
  {
    group: "Mathematics & Statistics",
    options: [
      "Algebra & Number Theory",
      "Analysis",
      "Geometry & Topology",
      "Applied & Computational Mathematics",
      "Statistics & Probability",
      "Discrete Mathematics & Theoretical Computer Science",
      "Optimization & Control Theory",
      "Financial Mathematics & Actuarial Science",
    ],
  },
  {
    group: "Computer Science & AI",
    options: [
      "Artificial Intelligence & Machine Learning",
      "Software Systems, Distributed Computing & HPC",
      "Cloud, Cybersecurity & Networking",
      "Data Science & Big Data Analytics",
      "Theoretical CS & Quantum Computing",
      "Human-Computer Interaction & Graphics",
      "IoT, Robotics & Embedded Systems",
      "Game Development & Interactive Media",
    ],
  },
  {
    group: "Engineering & Technology",
    options: [
      "Electrical, Electronic & Computer Engineering",
      "Mechanical, Aerospace & Robotics",
      "Chemical & Biomolecular Engineering",
      "Civil, Structural & Environmental Engineering",
      "Materials & Nano-Engineering",
      "Biomedical Engineering & MedTech",
      "Industrial Engineering & Operations Research",
    ],
  },
  {
    group: "Health, Medicine & Clinical Sciences",
    options: [
      "Clinical Medicine & Surgical Specialties",
      "Translational & Medical Research",
      "Public Health, Epidemiology & Policy",
      "Pharmacy & Pharmaceutical Sciences",
      "Healthcare AI & Digital Health",
      "Medical Imaging & Diagnostics",
    ],
  },
  {
    group: "Social Sciences, Business & Humanities",
    options: [
      "Business, Economics & Entrepreneurship",
      "Psychology, Cognitive & Behavioral Sciences",
      "Law, Public Policy & International Relations",
      "Arts, Design & Architecture",
      "Education & Social Development",
      "History, Philosophy & Religious Studies",
      "Media, Communications & Linguistics",
    ],
  },
];

export const HOBBIES: Record<string, string[]> = {
  beverages: [
    "Black Coffee",
    "Latte",
    "Espresso",
    "Cold Brew",
    "Matcha",
    "Thai Milk Tea",
    "Fruit/Bubble Tea",
    "Specialty Tea",
    "Energy Drinks",
    "Protein Shakes",
    "Water",
    "Craft Beer",
    "Wine",
    "Cocktails",
    "Kombucha",
    "Juice",
  ],
  fitness: [
    "Pilates",
    "Yoga",
    "Meditation",
    "Weightlifting",
    "CrossFit",
    "HIIT",
    "Calisthenics",
    "Running",
    "Cycling",
    "Swimming",
    "Hiking",
    "Rock Climbing",
    "Surfing",
    "Dance",
    "Martial Arts",
    "Boxing",
  ],
  sports: [
    "Badminton",
    "Basketball",
    "Football",
    "Volleyball",
    "Tennis",
    "Table Tennis",
    "E-Sports",
    "Muay Thai",
    "Pickleball",
    "Golf",
    "Ultimate Frisbee",
    "Softball",
    "Baseball",
    "Rugby",
    "Bowling",
    "Fencing",
    "Archery",
  ],
  gaming: [
    "PC (Steam/Epic)",
    "Console (PS/Xbox/Switch)",
    "Mobile Gaming",
    "Valorant",
    "League of Legends",
    "Dota 2",
    "RoV",
    "PUBG",
    "Apex Legends",
    "CS2/CS:GO",
    "Genshin Impact",
    "Honkai: Star Rail",
    "Cookie Run: Kingdom",
    "Minecraft",
    "Roblox",
    "Elden Ring",
    "Stardew Valley",
    "Strategy/Civilization",
    "Board Games",
    "TTRPG (D&D)",
    "Trading Card Games",
    "Chess",
    "Sudoku/Puzzles",
  ],
  music: [
    "Pop",
    "K-Pop",
    "T-Pop",
    "Rock",
    "Metal",
    "Indie/Alternative",
    "Jazz",
    "Classical",
    "R&B/Soul",
    "Hip-Hop/Rap",
    "EDM",
    "Lo-fi",
    "Synthwave/City Pop",
    "Soundtracks",
    "Podcasts",
    "Audiobooks",
    "Musicals",
  ],
  instruments: [
    "Vocals",
    "Piano/Keyboard",
    "Acoustic Guitar",
    "Electric Guitar",
    "Bass Guitar",
    "Ukulele",
    "Drum Kit",
    "Synthesizer",
    "DJ Controller",
    "Violin",
    "Viola",
    "Cello",
    "Flute",
    "Clarinet",
    "Saxophone",
    "Trumpet",
    "Thai Classical Instruments",
  ],
  creative: [
    "Photography (Digital)",
    "Photography (Film)",
    "Digital Illustration",
    "3D Modeling/CGI",
    "UI/UX Design",
    "Graphic Design",
    "Video Editing",
    "Motion Graphics",
    "Content Creation",
    "Traditional Painting",
    "Sketching/Drawing",
    "Calligraphy",
    "3D Printing",
    "Fashion Design",
    "Pottery/Ceramics",
  ],
  books: [
    "Sci-Fi",
    "Fantasy",
    "Mystery/Thriller",
    "Horror",
    "Literary Fiction",
    "Classic Literature",
    "Light Novels",
    "Popular Science & Tech",
    "Scientific Journals",
    "Philosophy",
    "Psychology",
    "History",
    "Biography/Memoir",
    "Self-Help",
    "Economics & Business",
    "Manga",
    "Webtoons/Manhwa",
    "Poetry",
    "Movies & TV",
  ],
  other: [
    "Birdwatching",
    "Vibe Coding",
    "AI Tinkering",
    "Cooking",
    "Baking",
    "Mixology",
    "Coffee Roasting",
    "Gardening",
    "Traveling",
    "Road Trips",
    "Camping",
    "Backpacking",
    "Fishing",
    "Volunteering",
    "Language Learning",
    "Collecting (Vinyl/Stamps)",
    "Interior Design",
    "Astrophotography",
    "Pet Care",
  ],
};

export const MED_SCHOOLS = [
  { value: "CU", label: "Chulalongkorn University (CU)" },
  { value: "MDSIR", label: "Mahidol University - Siriraj (MDSIR)" },
  { value: "MDRAMA", label: "Mahidol University - Ramathibodi (MDRAMA)" },
  { value: "CMU", label: "Chiang Mai University (CMU)" },
  { value: "KKU", label: "Khon Kaen University (KKU)" },
  { value: "PSU", label: "Prince of Songkla University (PSU)" },
  { value: "TU", label: "Thammasat University (TU)" },
  { value: "PCM", label: "Phramongkutklao College of Medicine (PCM)" },
  { value: "SWU", label: "Srinakharinwirot University (SWU)" },
  { value: "NU", label: "Naresuan University (NU)" },
  {
    value: "NMU",
    label: "Navamindradhiraj University - Vajira Hospital (NMU)",
  },
  { value: "Other", label: "Other" },
];

export const MED_DUAL_TYPES = [
  "MD/PhD",
  "MD/Master of Management (MD/MM)",
  "MD/MBA",
  "MD/MEng",
  "MD/MSc",
  "Other",
];

export const MED_SPECIALTIES = [
  "Undecided / Exploring",
  "Internal Medicine - อายุรศาสตร์",
  "Surgery - ศัลยศาสตร์",
  "Pediatrics - กุมารเวชศาสตร์",
  "OB-GYN - สูตินรีเวชวิทยา",
  "Orthopedics - ศัลยศาสตร์ออร์โธปิดิกส์",
  "Emergency Medicine - เวชศาสตร์ฉุกเฉิน",
  "Radiology - รังสีวิทยา",
  "Anesthesiology - วิสัญญีวิทยา",
  "Psychiatry - จิตเวชศาสตร์",
  "Ophthalmology - จักษุวิทยา",
  "Otolaryngology - โสต ศอ นาสิกวิทยา",
  "Dermatology - ตจวิทยา",
  "Pathology - พยาธิวิทยา",
  "Family Medicine - เวชศาสตร์ครอบครัว",
  "Rehabilitation Medicine - เวชศาสตร์ฟื้นฟู",
  "Other",
];

export const MED_DEGREES = ["MD", "MBBS", "MBChB"];
